### ISSUE TITLE
Similar package / implementation

### ISSUE THREAD

**Issue by d2g** [hashicorp/logutils#5]
Hi, I wasn't aware of your package and have written a very similar one. https://github.com/d2g/logfilter

Not sure if you wanted to review the api style or functionality to see if you were interested in merging/pulling functionality across etc.

**Comment by freeekanayaka** [comment]
It seems that logfilter has a few more features wrt logutils. In particular it has the ability to set log levels by package, which I find quite important. With logutils the only way to do that is to create different loggers with different levels and pass them around appropriately.

Yet another similar package is CoLog:

https://texlution.com/post/colog-prefix-based-logging-in-golang/

**Comment by josephholsten** [comment]
@freeekanayaka think you could write up a quick example of that? I'm trying to doc the differences here, this would be a useful part of such.

**Comment by jefferai** [comment]
You may also want to look at https://github.com/hashicorp/go-hclog which is very new. It supports prefixes/derived loggers, pinning args to loggers, stdlog compatibility, and some other things. It's what we're moving HC stuff to as it implements some standard logging guidelines we have built internally.

**Comment by josephholsten** [comment]
@jefferai <3

**Comment by freeekanayaka** [comment]
@jefferai thanks for the pointer. The go-hclog package indeed has a stdlog compatibility layer, however it somehow seems a "secondary" option, meant only for when you need to interface with legacy code or code that you can't change or don't want to. All in all it seems to diverge a bit from the philosophy of logutils, and join the already vast group of alternate (wrt stdlib) logging systems. I might have missed that, but is someone proposing to enahnce stdlib's logging for Go 2 ? If you know. That'd be everyone's favorite option, I take.

@josephholsten if there's desire on the colog's part to join forces, I might do what you ask or help, but I think we need to hear from upstream first (I saw you opened an issue). Regarding logutils, it seems that HC is moving to another direction with go-hclog, so I assume logutils it's or will become kind of legacy.

**Comment by freeekanayaka** [comment]
@jefferai btw, are HC's standard logging guidelines publicly available? if not, could they be?

**Comment by freeekanayaka** [comment]
Re Go 2 logging experiences: https://github.com/golang/go/wiki/ExperienceReports#logging

**Comment by jefferai** [comment]
@freeekanayaka It's actually more an evolution or special-casing of logutils than an alternate logging system.

Unlike many third-party logging systems, which are generally opinionated about what and when and why, the purpose of hclog is simply for us to standardize on formatting across our tools. This has knock-on effects because it allows us to also standardize on machine readable (e.g. JSON) output.

Logutils' philsophy is the simplest possible thing that could work but it ends up with some jagged edges. For instance, it forces a lot of boilerplate typing ("[INFO]", including brackets) and if you typo you end up sending your logs to the wrong level instead of the compiler catching it. There are also some minor but worthwhile performance operations you can achieve with boolean level checks.

If you compare it to logrus or zap you'll see that it is far simpler, because it is not laser-focused on performance or strong typing to the point where you need a totally new system. Instead it just allows our coders to still use very simple log constructions and functions while ensuring that the logs from Vault look like the logs from Nomad look like the logs from Consul and so on. So a way to think of it might be "the simplest possible thing that could standardize our logging".

**Comment by mitchellh** [comment]
Going to close this issue since I don't think we have any intent to merge projects from 2015 and we've also moved on mostly to use go-hclog.
